@startuml

top to bottom direction
skinparam linetype ortho

class Character<Attackable> {
  + Character(String, float, float): 
  - name: String
  - attackDamage: float
  - health: float
  + heal(float): void
  + isDead(): boolean
  + getHealth(): float
  + attack(Attackable): void
  + takeDamage(float): void
  + getName(): String
  # attack0(Attackable): void
  # canAttack(Attackable): boolean
  + getAttackDamage(): float
}
class Hero {
  + Hero(String, int, float, float): 
  + Hero(String, int, float, float, Weapon?): 
  - level: int
  - weapon: Weapon?
  + getWeapon(): Weapon?
  + takeDamage(float): void
  + getLevel(): int
  # attack0(Monster): void
}
class Monster {
  + Monster(String, float, float): 
  # attack0(Hero): void
}
class Weapon {
  + Weapon(String, float): 
  - name: String
  - damage: float
  + getDamage(): float
  + getName(): String
}

Hero       -[#000082,plain]-^  Character 
Monster    -[#000082,plain]-^  Character 
@enduml
